---
- hosts: space
  pre_tasks:
    - name: Detect chroot
      set_fact:
        chroot: "{{ ansible_connection == 'chroot' or 'container' in ansible_env }}"
      tags: always
    - name: Load secrets
      include_vars: '{{ item }}'
      with_first_found:
        - files:
            - /etc/ansible/secrets.yml
            - secrets.yml
          skip: true
      tags:
        - radius
  roles:
    - space_server

# vim: set ts=2 sw=2 et:
