---
- name: Install network configuration
  copy:
    dest: '/etc/systemd/network/10-eth0.network'
    src: eth0.network
    owner: root
    group: root
    mode: 0644
  tags:
  - networkd-config

- name: Disable unused services
  systemd:
    name: '{{ item }}'
    enabled: no
  with_items:
  - hciuart.service
  - remote-fs.target
  - rsync.service
  - bluetooth.service
  tags:
  - systemd

- name: Remove broken service links
  file:
    path: '{{ item }}'
    state: absent
  with_items:
  - /etc/systemd/system/bluetooth.target.wants
  tags:
  - systemd

- import_tasks: console.yml
  tags: console
- import_tasks: jumbotron.yml
  tags: jumbotron
- import_tasks: autologin.yml
  tags: autologin
- import_tasks: irssi.yml
  tags: irssi
- import_tasks: fakta.yml
  tags: fakta

# vim: set ts=2 sw=2 et:
