---
- import_tasks: esmil.yml
  tags:
    - users
    - esmil
- import_tasks: ast.yml
  tags:
    - users
    - ast
- import_tasks: flummer.yml
  tags:
    - users
    - flummer
- import_tasks: riiiis.yml
  tags:
    - users
    - riiiis
- import_tasks: knielsen.yml
  tags:
    - users
    - knielsen
- import_tasks: k2os.yml
  tags:
    - users
    - k2os

# vim: set ts=2 sw=2 et:
