# if not running interactively, don't do anything
[[ $- != *i* ]] && return

set -o vi

export PS1='\[\e[1;32m\]\u\[\e[00m\]@\[\e[0;32m\]\h\[\e[1;34m\]\w\[\e[00m\]\$ '
unset PROMPT_COMMAND
export -n PROMPT_COMMAND

# directory listing
if type dircolors > /dev/null 2>&1; then
  eval "$(dircolors -b)"
fi
alias ls='ls --color=auto -F'
alias ll='ls -Ahl'

# some more alias to avoid making mistakes:
alias rm='rm -ri'
alias cp='cp -rid'
alias mv='mv -i'

# editor
export EDITOR='vim'
alias vi='vim'

# pager
export PAGER='less'
export LESS='-FRXS'

# systemd
alias start='systemctl --user start'
alias stop='systemctl --user stop'
alias restart='systemctl --user restart'
alias status='systemctl --user status'

stty -ixon
cd
