---
- name: Configure chrony.conf
  copy:
    dest: '/etc/chrony.conf'
    src: chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: restart chronyd

- name: Create service drop-in directory
  file:
    dest: '/etc/systemd/system/chronyd.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Start chrony after networks are configured
  copy:
    dest: '/etc/systemd/system/chronyd.service.d/wait-online.conf'
    src: wait-online.conf
    owner: root
    group: root
    mode: 0644

- name: Enable chronyd service
  systemd:
    name: chronyd.service
    enabled: yes
    masked: no
    state: started
  when: not chroot
- name: '- when in chroot'
  command: systemctl enable chronyd.service
  when: chroot

# vim: set ts=2 sw=2 et ft=yaml:
